DROP TABLE IF EXISTS STUDENTGRADES;
DROP TABLE IF EXISTS STUDENTINCLASSROOM;
DROP TABLE IF EXISTS CLASSROOMS;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS SUBJECTS;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS(

id identity primary key,
password VARCHAR(30)

);

CREATE TABLE IF NOT EXISTS ADMINS(
id primary key,
FOREIGN KEY(id) FROM USERS(id)
)

CREATE TABLE IF NOT EXISTS SUBJECTS(

id identity primary key,
name VARCHAR(50),
course INT,
description VARCHAR(30)

);

CREATE TABLE IF NOT EXISTS TEACHERS(

id primary key,
dni VARCHAR(9),
name VARCHAR(100),
age DATE,
idsub INT,
FOREIGN KEY(id) FROM USERS(id),
FOREIGN KEY(idsub) FROM SUBJECTS(id)

);

CREATE TABLE IF NOT EXISTS STUDENTS(

id primary key,
dni VARCHAR(9),
name VARCHAR(100),
age DATE,
course INT,
FOREIGN KEY(id) FROM USERS(id)

);

CREATE TABLE IF NOT EXISTS CLASSROOMS(

id primary key,
name VARCHAR(100) NOT NULL,
course INT NOT NULL,
idsub INT NOT NULL,
idteach INT NOT NULL,
qstudents INT NOT NULL,
FOREIGN KEY(idsub) FROM SUBJECTS(id),
FOREIGN KEY(idteach) FROM TEACHERS(id),
CHECK(qstudents<=20)

);

CREATE TABLE IF NOT EXISTS STUDENTSINCLASSROOMS(

id primary key,
idstud int,
idcr int,
idsub int,
FOREIGN KEY(idstud) FROM STUDENTS(id),
FOREIGN KEY(idsub) FROM SUBJECTS(id)

);

CREATE TABLE IF NOT EXISTS STUDENTGRADES(

id primary key,
idstudentincr int,
grade int,
FOREIGN KEY(idstudentincr) FROM STUDENTINCLASSROOM(id)

);